server:
  port: 8080

spring:
  application:
    name: auth

  mvc:
    problemdetails:
      enabled: true

store:
  jwt:
    secretKey: ${STORE_JWT_SECRET_KEY:changeit}
  token:
    duration: ${STORE_TOKEN_DURATION:3600000} # 1 hour in milliseconds
    https: ${STORE_TOKEN_HTTPS:true}

logging:
  level:
    root: info
    store: debug